apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: worker 
  template:
    metadata:
      labels:
        component: worker
    spec:
      containers:
        - name: worker
          image: katarinacimesa/multi-worker
          # TODO: eventually environment variables to connect to redis
          # no other object needs to directly connect and send requests to the multi-worker
          # worker will send requests, but it will never get a reqest INTO itself
          # no ports needed
          env:
            - name: REDIS_HOST
              value: redis-cluster-ip-service
            - name: REDIS_PORT
              value: '6379'